# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"
# HISTTIMEFORMAT="%F %T "

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/.zsh/custom"

# tmux plugin
# ZSH_TMUX_AUTOSTART=true  # (do not do this, vscode don't need tmux)
ZSH_TMUX_AUTOQUIT=true

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	git
	tmux
	colored-man-pages
	colorize
	extract
	command-not-found
	autojump
	zsh-vi-mode
	zsh-autosuggestions
	zsh-syntax-highlighting  # This must go at the end
)

# zsh-completions (initialized before `source "$ZSH/oh-my-zsh.sh"`)
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

# git completion for switch is not working now (23/03/15)
# Using workaround provided by [this issue](https://github.com/ohmyzsh/ohmyzsh/issues/8105)
# And there is a [blog](https://oliverspryn.blog/adding-git-completion-to-zsh-60f3b0e7ffbc)
# Using this solution currently makes gco worse (losing some info, but acceptable), but gsw works
# I guess only fpath is required (following zsh-completions plugin) because omz should do all other jobs (and this works)
#
# Load completion files from the ~/.zsh/completion directory.
# zstyle ':completion:*:*:git:*' script ~/.zsh/completion/git-completion.bash
fpath=(~/.zsh/completion $fpath)
# autoload -Uz compinit && compinit

source "$ZSH/oh-my-zsh.sh"

# https://github.com/zsh-users/zsh-autosuggestions/issues/511
zle_bracketed_paste=()

# Time to wait for additional characters in a sequence
# https://www.johnhawthorn.com/2012/09/vi-escape-delays/
KEYTIMEOUT=1 # corresponds to 10ms

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

source ~/.shell/functions.sh

path_prepend "$HOME/.local/bin"
path_prepend "$HOME/.dotfiles/bin"

source ~/.shell/external.sh

source ~/.shell/proxy.sh

source ~/.shell/aliases.sh

# Use vim as the editor
export EDITOR=vim

# Allow local customizations in the ~/.shell_local_after file
if [ -f ~/.shell_local_after ]; then
    source ~/.shell_local_after
fi
